/// <reference types="Cypress" />

declare namespace Cypress {
    interface Chainable {
        login(username: string, password: string): Cypress.Chainable<JQuery>;
        verifyPageTitle(title: string): Cypress.Chainable<JQuery>;
        verifySuccessMessage(messageText: string): Cypress.Chainable<JQuery>;
        logout(): Cypress.Chainable<JQuery>;
        verifyNoErrors(): Cypress.Chainable<JQuery>;
        getProjectNameFromXML(filePath: string): Cypress.Chainable<String>;
        getResourceNameFromXML(filePath: string): Cypress.Chainable<String>;
        selectMoreAction(item: string, action:string): Cypress.Chainable<JQuery>;
        getInstallDirectory(): Cypress.Chainable<JQuery>;
        verifySuccessMessages(messageTexts: string[]): Cypress.Chainable<JQuery>;
        getWebUserAutoGeneratedPassword(): Cypress.Chainable<JQuery>;
        verifyErrorMessage(messageText: string): Cypress.Chainable<JQuery>;
        loginClient(username: string, password: String, checkSuccessMessage: boolean): Cypress.Chainable<JQuery>;
        navigateToThePageByName(menuSelector: string, submenuTitle: string): Cypress.Chainable<JQuery>;
        uploadFile(fileName: string, importType: string): Cypress.Chainable<JQuery>;
        startService(serviceName: string): Cypress.Chainable<JQuery>;
        parseXmlToJson(filepath: string): Cypress.Chainable<String>;
        parseJsonToXml(filepath: string, data: string): Cypress.Chainable<String>;
        getAdminUserLinks(): Cypress.Chainable<Array<String>>;
    }
}